### ISSUE TITLE
Invalid Field

### ISSUE THREAD

**Issue by MarcusCaepio** [widhalmt/check_logstash#27] opened 2019-02-07 13:42 UTC
What does this mean?

./check_logstash -H 127.0.0.1
./check_logstash:203:in `rescue in get': .monitoring-logstash.events.in (CheckLogstash::Result::InvalidField)
        from ./check_logstash:195:in `get'
        from ./check_logstash:198:in `get'
        from ./check_logstash:191:in `get'
        from ./check_logstash:426:in `block in inflight_events_health'
        from ./check_logstash:425:in `each'
        from ./check_logstash:425:in `inflight_events_health'
        from ./check_logstash:373:in `health'
        from ./check_logstash:87:in `run'
        from ./check_logstash:522:in `<main>'

**Comment by MarcusCaepio** [comment] 2019-02-12 08:10
Hello? :)
Additional Info: I am not using the main pipeline. I have different named pipelines.
When I use this plugin on a default logstash pipeline called main, it works

**Comment by rnicksic** [comment] 2019-03-22 16:45
I'm also getting the identical output when running this on a logstash instance with 3 pipelines

```
./check_logstash.rb:203:in `rescue in get': .monitoring-logstash.events.in (CheckLogstash::Result::InvalidField)
        from ./check_logstash.rb:195:in `get'
        from ./check_logstash.rb:198:in `get'
        from ./check_logstash.rb:191:in `get'
        from ./check_logstash.rb:426:in `block in inflight_events_health'
        from ./check_logstash.rb:425:in `each'
        from ./check_logstash.rb:425:in `inflight_events_health'
        from ./check_logstash.rb:373:in `health'
        from ./check_logstash.rb:87:in `run'
        from ./check_logstash.rb:522:in `<main>'
```

**Comment by MarcusCaepio** [comment] 2019-03-22 17:18
@widhalmt is this plugin still supported?

**Comment by widhalmt** [comment] 2019-03-22 17:31
@MarcusCaepio yes. I'lm on this right now.

**Comment by widhalmt** [comment] 2019-03-22 18:03
I can not reproduce this. Did you try the latest commit? I have several pipelines and I renamed them so there is no "main" anymore. I do get a valid output.

**Comment by rnicksic** [comment] 2019-03-22 18:24
I tried the latest commit and I'm still getting the same error.

**Comment by widhalmt** [comment] 2019-03-22 18:41
@rnicksic could you paste the output of `curl localhost:9600` on your Logstash host (or whatever you use to get the output of the API)

**Comment by rnicksic** [comment] 2019-03-22 18:49
```
curl  http://obc-logstash1:9600/_node/stats?pretty
{
  "host" : "obc-logstash1",
  "version" : "6.6.1",
  "http_address" : "10.120.128.52:9600",
  "id" : "634cbc15-7d9b-440e-9e23-853a65aa1133",
  "name" : "obc-logstash1",
  "jvm" : {
    "threads" : {
      "count" : 126,
      "peak_count" : 129
    },
    "mem" : {
      "heap_used_percent" : 7,
      "heap_committed_in_bytes" : 8555069440,
      "heap_max_in_bytes" : 8555069440,
      "heap_used_in_bytes" : 623995400,
      "non_heap_used_in_bytes" : 211906488,
      "non_heap_committed_in_bytes" : 248504320,
      "pools" : {
        "survivor" : {
          "peak_used_in_bytes" : 34865152,
          "used_in_bytes" : 2099016,
          "peak_max_in_bytes" : 34865152,
          "max_in_bytes" : 34865152,
          "committed_in_bytes" : 34865152
        },
        "old" : {
          "peak_used_in_bytes" : 594861872,
          "used_in_bytes" : 594861872,
          "peak_max_in_bytes" : 8241020928,
          "max_in_bytes" : 8241020928,
          "committed_in_bytes" : 8241020928
        },
        "young" : {
          "peak_used_in_bytes" : 279183360,
          "used_in_bytes" : 27034512,
          "peak_max_in_bytes" : 279183360,
          "max_in_bytes" : 279183360,
          "committed_in_bytes" : 279183360
        }
      }
    },
    "gc" : {
      "collectors" : {
        "old" : {
          "collection_time_in_millis" : 234,
          "collection_count" : 2
        },
        "young" : {
          "collection_time_in_millis" : 44096,
          "collection_count" : 672
        }
      }
    },
    "uptime_in_millis" : 17839268
  },
  "process" : {
    "open_file_descriptors" : 185,
    "peak_open_file_descriptors" : 186,
    "max_file_descriptors" : 16384,
    "mem" : {
      "total_virtual_in_bytes" : 13205073920
    },
    "cpu" : {
      "total_in_millis" : 1921910,
      "percent" : 1,
      "load_average" : {
        "1m" : 0.13,
        "5m" : 0.1,
        "15m" : 0.09
      }
    }
  },
  "events" : {
    "in" : 1170123,
    "filtered" : 1170123,
    "out" : 1170123,
    "duration_in_millis" : 5143600,
    "queue_push_duration_in_millis" : 386243
  },
  "pipelines" : {
    "maillog" : {
      "events" : {
        "duration_in_millis" : 954534,
        "in" : 194770,
        "out" : 194770,
        "filtered" : 194770,
        "queue_push_duration_in_millis" : 362
      },
      "plugins" : {
        "inputs" : [ {
          "id" : "4a5ea94352340ec71689ab7d940e466843388d86963b19d9c1233422dcc7bfac",
          "events" : {
            "out" : 194770,
            "queue_push_duration_in_millis" : 362
          },
          "current_connections" : 1,
          "name" : "beats",
          "peak_connections" : 1
        } ],
        "filters" : [ {
          "id" : "505846c38989dca112c7682b82b0f49fab67eec6a30813c6d1d13b498d79f673",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 0,
            "out" : 0
          },
          "matches" : 0,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "729cb7a16799da99d8395a303cf26e120546cad61d9b9cc45c7b190fcd2e03e4",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 0,
            "out" : 0
          },
          "matches" : 0,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "3c39a604770be4ca0755f344d43c8ab516c0e75b3eea7d493f6b74b9ca70bee6",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 0,
            "out" : 0
          },
          "matches" : 0,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "a79f02ae9887e3ad9bfee5c453f781a6575d0776639c5298d2b4e66689896a4e",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 0,
            "out" : 0
          },
          "matches" : 0,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "98351ff65a4c72474a2131b04543acf08570f4fac38276f8a72c61069beace1b",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 0,
            "out" : 0
          },
          "matches" : 0,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "a6211753a22fa8801bb618d92fb8b28d12b07ead0032bfd9422282386db1ed53",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 0,
            "out" : 0
          },
          "matches" : 0,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "d00d89f697961bf37b01f501d61ee5210782ac0d6a695016292c672ae7fe89d2",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 68,
            "out" : 68
          },
          "matches" : 68,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "398a62f455acc002b68c6b6aa2cd27195b1504c051634ccb0ecc13fa5fdfcc26",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 0,
            "out" : 0
          },
          "matches" : 0,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "1752a5e3ee7d5752192fe49222a7f97857ff35605c48d3649be8e4c7d854b65a",
          "events" : {
            "duration_in_millis" : 3416,
            "in" : 86227,
            "out" : 86227
          },
          "matches" : 86227,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "1dee5c1fe0688f3c42a90a622612076a2de80534db035ef09a494ff576fff54a",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 0,
            "out" : 0
          },
          "matches" : 0,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "7d92b91a87a4b70338de316072f22092b87eda5e505d8168ee03c4bb4413196c",
          "events" : {
            "duration_in_millis" : 2333,
            "in" : 63359,
            "out" : 63359
          },
          "name" : "kv"
        }, {
          "id" : "f41ec52d16db27d98d463cf4a3f2cda8d293787058073f96404e68063a26cf3e",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 0,
            "out" : 0
          },
          "matches" : 0,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "b234cfce378c8af3d9cb600a7c40be872f654c106e9a4c724e22c61d53ad00c3",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 0,
            "out" : 0
          },
          "matches" : 0,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "7d9f1a591e96b3e2ecb3d87f563d8952254cd8bfcf6e9913364362a5f84a2157",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 0,
            "out" : 0
          },
          "name" : "mutate"
        }, {
          "id" : "a2d911adc2d38bded650d9bfe9f8c7cd39877694a0617273481050ae9f7a52f1",
          "events" : {
            "duration_in_millis" : 5663,
            "in" : 194770,
            "out" : 194770
          },
          "matches" : 194770,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "bce46577d5362e90b49a112e416fe719a222ede04e71c88c502476f83034308b",
          "events" : {
            "duration_in_millis" : 878,
            "in" : 19016,
            "out" : 19016
          },
          "matches" : 18922,
          "failures" : 94,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "bb805a1ab7ffc069ea6439db4a7bb9a1f490176976a3f6d31ec60561d559a521",
          "events" : {
            "duration_in_millis" : 427,
            "in" : 18185,
            "out" : 18185
          },
          "matches" : 18185,
          "failures" : 0,
          "patterns_per_field" : {
            "postfix_relay" : 1
          },
          "name" : "grok"
        }, {
          "id" : "13eed4c04ca0abfc359b50cccf16e8d16e27132a546116dffab331bb38f0ce28",
          "events" : {
            "duration_in_millis" : 5,
            "in" : 180,
            "out" : 180
          },
          "matches" : 180,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "dfa190b6b77245d67e407e4251b314f594103b665cfc3802137f21afef4479bd",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 0,
            "out" : 0
          },
          "matches" : 0,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "55cd4c4e9f370b757978dd8db41b31aebf844e6ffa32455cfbad0b2c28fff594",
          "events" : {
            "duration_in_millis" : 316,
            "in" : 14370,
            "out" : 14370
          },
          "matches" : 14370,
          "failures" : 0,
          "patterns_per_field" : {
            "postfix_client" : 1
          },
          "name" : "grok"
        }, {
          "id" : "f8d7ae9a04e28d41caacbf5bd82357b1141aed5a564468cd1f8027f7c336e3d5",
          "events" : {
            "duration_in_millis" : 31,
            "in" : 530,
            "out" : 530
          },
          "matches" : 530,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "6f2c4b699a4a0ee8ac72eebbd172dcb3a33688d81b00f7a642914ab7c931ab66",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 0,
            "out" : 0
          },
          "matches" : 0,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "14635bb44bb652e811a9a4caf36a17f6018964119b0f7d4236d05f0de918bfb3",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 0,
            "out" : 0
          },
          "matches" : 0,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "ff9dcf37eb2a776dd0fdeaacc5396d4d4e60419e6faa05d1fd6447741d7796d7",
          "events" : {
            "duration_in_millis" : 4745,
            "in" : 194770,
            "out" : 194770
          },
          "name" : "mutate"
        }, {
          "id" : "29d0cc6e867dd9328b54fb37438fcaf86bbb12572a04f84ed10ba3456b1ebc3b",
          "events" : {
            "duration_in_millis" : 427,
            "in" : 14370,
            "out" : 14370
          },
          "matches" : 14370,
          "failures" : 0,
          "patterns_per_field" : {
            "postfix_command_counter_data" : 1
          },
          "name" : "grok"
        }, {
          "id" : "cc00c705581dbce320e7c1e83c10fd1a7f65213a32c55bd9ad3f20d167de65cd",
          "events" : {
            "duration_in_millis" : 2011,
            "in" : 57959,
            "out" : 57959
          },
          "matches" : 15047,
          "failures" : 42912,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "99c6eaf67533936a54ddc88940d6989310f2086bdb3f67da8addcd933dac1a48",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 0,
            "out" : 0
          },
          "matches" : 0,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "a644cb005f66cbb05eb04232db9352922317a6b44320122dd9c290d9afa15dee",
          "events" : {
            "duration_in_millis" : 719,
            "in" : 30790,
            "out" : 30790
          },
          "matches" : 30790,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "bca2a3ddc41229c8d43b9a9bdbee7aa13acb70ba6834cb7a113e2bbfa94379cd",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 0,
            "out" : 0
          },
          "matches" : 0,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "4f562219cc28356b963e6be530d33f5322ea5548f7c31e8f9389fe64cf3f560e",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 0,
            "out" : 0
          },
          "matches" : 0,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "a3591ccf537723116c2248cc7ae23dfd484e289fc9ae4f82478e2a31444b80f8",
          "events" : {
            "duration_in_millis" : 205,
            "in" : 18185,
            "out" : 18185
          },
          "matches" : 18185,
          "failures" : 0,
          "patterns_per_field" : {
            "postfix_delays" : 1
          },
          "name" : "grok"
        }, {
          "id" : "981906eae398abe7b07a20abb5a1fd3c3d8c8aad1792e395c121f435f4808886",
          "events" : {
            "duration_in_millis" : 6110,
            "in" : 194770,
            "out" : 194770
          },
          "matches" : 2,
          "name" : "date"
        } ],
        "outputs" : [ {
          "id" : "02b5d8a7342f5cd50933284f7cd1052bc452136d2e56aef7c6b5c74a2657c2f5",
          "documents" : {
            "successes" : 194770
          },
          "events" : {
            "duration_in_millis" : 807343,
            "in" : 194770,
            "out" : 194770
          },
          "bulk_requests" : {
            "successes" : 16146,
            "responses" : {
              "200" : 16146
            }
          },
          "name" : "elasticsearch"
        } ]
      },
      "reloads" : {
        "last_error" : null,
        "successes" : 0,
        "last_success_timestamp" : null,
        "last_failure_timestamp" : null,
        "failures" : 0
      },
      "queue" : {
        "type" : "memory"
      }
    },
    "gateway_monitor" : {
      "events" : {
        "duration_in_millis" : 2361520,
        "in" : 251372,
        "out" : 251372,
        "filtered" : 251372,
        "queue_push_duration_in_millis" : 17
      },
      "plugins" : {
        "inputs" : [ {
          "id" : "187dd38a7741518b9c5527d820dfaa62107e6def46d4e0a9e4093bc12bcd3fb4",
          "events" : {
            "out" : 0,
            "queue_push_duration_in_millis" : 0
          },
          "name" : "file"
        }, {
          "id" : "gateway_monitor_filebeat_input",
          "events" : {
            "out" : 251372,
            "queue_push_duration_in_millis" : 17
          },
          "current_connections" : 5,
          "name" : "beats",
          "peak_connections" : 5
        } ],
        "filters" : [ {
          "id" : "5e5ad00f9d35a35bfd6c02d0ea1a79ae5fd40e8a6b0088dda8b629c2bbe6523f",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 52,
            "out" : 52
          },
          "matches" : 52,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "b46dab8908b44916ece652051a34b0a746a5a7d1c3ba41ade9731bf9f488646f",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 29,
            "out" : 29
          },
          "matches" : 29,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 6
          },
          "name" : "grok"
        }, {
          "id" : "5ecd52a58eac9148fd7c6f799b2c9c0910d8aece9b5eed3d2237c61901e00bc7",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 52,
            "out" : 52
          },
          "matches" : 52,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "cb9958a8b68a64f13f95d90e926d676ea2e056adbb31786454cc718095fdca77",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 41,
            "out" : 41
          },
          "matches" : 41,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "47400e3c930c595030b75fcf452c822a47be19da019d46d2f4953f00d2a971d9",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 0,
            "out" : 0
          },
          "matches" : 0,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 2
          },
          "name" : "grok"
        }, {
          "id" : "c41c2b055d414433942f550871bbf29e6eea3221e0b7486dc4c4a53dd6b38883",
          "events" : {
            "duration_in_millis" : 928,
            "in" : 57111,
            "out" : 57111
          },
          "matches" : 57111,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 6
          },
          "name" : "grok"
        }, {
          "id" : "9dcfd5e8bd7964db6d255d70a8cc68b2b2a1d6798d56d51a51534119892cb071",
          "events" : {
            "duration_in_millis" : 19,
            "in" : 1542,
            "out" : 1542
          },
          "matches" : 1542,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "44560313d03444efa227cb40d203bef29a6f2722db7be3ad7f02ef8f8c64439d",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 0,
            "out" : 0
          },
          "matches" : 0,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 5
          },
          "name" : "grok"
        }, {
          "id" : "86ea336ba20f0ddef552fc5b123c7f15fb8df094682a469b6b891011ed340e02",
          "events" : {
            "duration_in_millis" : 8,
            "in" : 12033,
            "out" : 12033
          },
          "matches" : 12033,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 2
          },
          "name" : "grok"
        }, {
          "id" : "9444b9d683f5850fd1c863db24e7fbfdfa300554754222c784f62dddbddb97db",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 24,
            "out" : 24
          },
          "matches" : 24,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "8400db007e364cf0e4beb00b281ebd72ebfa1afe3720d77395a5367dbc443afb",
          "events" : {
            "duration_in_millis" : 1128,
            "in" : 152599,
            "out" : 152599
          },
          "name" : "geoip"
        }, {
          "id" : "e37ebda749bbba2dc35872eccc6875e36d65b62b94a98a0f41883ec0ed3a7402",
          "events" : {
            "duration_in_millis" : 132,
            "in" : 12858,
            "out" : 12858
          },
          "matches" : 12858,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "fe940e02d12313bf8b5cc6c341c8b8eff06ee165c49300fe964dc42b114e9b7a",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 57,
            "out" : 57
          },
          "matches" : 57,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 2
          },
          "name" : "grok"
        }, {
          "id" : "fbd038a52e2f4672c4f8f899e290489085aa434b6d5637ef6d63081b60511e44",
          "events" : {
            "duration_in_millis" : 1,
            "in" : 400,
            "out" : 400
          },
          "matches" : 400,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 4
          },
          "name" : "grok"
        }, {
          "id" : "121592746d001899ba2e0d2fd0769268c7cd587296997abb9f2fd7c5d3bee225",
          "events" : {
            "duration_in_millis" : 318,
            "in" : 34438,
            "out" : 34438
          },
          "matches" : 34438,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 3
          },
          "name" : "grok"
        }, {
          "id" : "e202f7ae9bf8a6064be329d42f7bd5b7e30d961a487ce61beadaa77a2a12ec3a",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 198,
            "out" : 198
          },
          "matches" : 198,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 3
          },
          "name" : "grok"
        }, {
          "id" : "8d22be5a86ca899e6d8bcca01830efcb5376024f2fa4b7e972991937940aeefa",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 2,
            "out" : 2
          },
          "matches" : 2,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 2
          },
          "name" : "grok"
        }, {
          "id" : "7e0a54d042b885b2b590741ec01d3d23e3434a69837e3e124ed4a4925ac605c3",
          "events" : {
            "duration_in_millis" : 1,
            "in" : 218,
            "out" : 218
          },
          "matches" : 218,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 5
          },
          "name" : "grok"
        }, {
          "id" : "86a8643f4ba7f156804d0a49cfd725258167e0af5b42a7e5524fd3da31ccaf37",
          "events" : {
            "duration_in_millis" : 57,
            "in" : 1296,
            "out" : 1296
          },
          "matches" : 1296,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "03376bbc78006a735b15ecbf679b9735d85426f7e027f57a3fbaa084249e61b7",
          "events" : {
            "duration_in_millis" : 35,
            "in" : 13109,
            "out" : 13109
          },
          "matches" : 13109,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 4
          },
          "name" : "grok"
        }, {
          "id" : "c26277bc3d27652530c347217b09ab3a83440a203a684601c6318f37128f82ef",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 38,
            "out" : 38
          },
          "matches" : 38,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "8190108d319f0ea79db8394eb6791f497d26838996b52fb1adc4e699a95744df",
          "events" : {
            "duration_in_millis" : 6,
            "in" : 1662,
            "out" : 1662
          },
          "matches" : 1662,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 5
          },
          "name" : "grok"
        }, {
          "id" : "b03a2405d123d6132696e146ac9f5dfeed98ce22af8e6dddab3242df1e170283",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 139,
            "out" : 139
          },
          "matches" : 139,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "2ce722f83f8209b1379013e61bbead0ea888604309888030a18dbf6e482bd651",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 0,
            "out" : 0
          },
          "matches" : 0,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 2
          },
          "name" : "grok"
        }, {
          "id" : "6d23922ad13f381c66f4dfd461b15f4162f1403f8f241b83f4944ad911825a96",
          "events" : {
            "duration_in_millis" : 9005,
            "in" : 251372,
            "out" : 251372
          },
          "matches" : 251369,
          "failures" : 3,
          "patterns_per_field" : {
            "message" : 2
          },
          "name" : "grok"
        }, {
          "id" : "ab9ab4edd6737649077911fe030a4c3ecc198b40b717444c96399d984db33292",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 0,
            "out" : 0
          },
          "matches" : 0,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 5
          },
          "name" : "grok"
        }, {
          "id" : "2af364cbd2fde85499e56a76a003cf71409f5d59f20185d9a113cc5097062e8c",
          "events" : {
            "duration_in_millis" : 359,
            "in" : 69866,
            "out" : 69866
          },
          "matches" : 69866,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 21
          },
          "name" : "grok"
        }, {
          "id" : "5cdf1f6ef678bc65b8d643c77329c4eb2af7d33f7debda6f83e439ad5f213e30",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 0,
            "out" : 0
          },
          "matches" : 0,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "ec163ef78176554a7c1d56fca6a6b22885c526c5c8265ff3c2d40e87c28ceaa9",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 0,
            "out" : 0
          },
          "matches" : 0,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "829c6b5e4e1a86ff7a0c97c5fc8581839a7836403ba9f42cbbd5c0bd5062e00d",
          "events" : {
            "duration_in_millis" : 1274,
            "in" : 251369,
            "out" : 251369
          },
          "matches" : 251369,
          "name" : "date"
        }, {
          "id" : "9ac932fe3b2bc82393b79fd6c54783c3889445a857f621a01682f9da9d485059",
          "events" : {
            "duration_in_millis" : 68,
            "in" : 16205,
            "out" : 16205
          },
          "matches" : 16205,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 2
          },
          "name" : "grok"
        }, {
          "id" : "5eef47b2f1d3f8274ffb0d1b589273ae0b7e3d0c3cd5fee9c360a095c598b82a",
          "events" : {
            "duration_in_millis" : 0,
            "in" : 2630,
            "out" : 2630
          },
          "matches" : 2630,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 1
          },
          "name" : "grok"
        }, {
          "id" : "7b8ea47995cb6aed6b83867badc00a257817d833d003e01392bbd8a944900d6e",
          "events" : {
            "duration_in_millis" : 74,
            "in" : 22458,
            "out" : 22458
          },
          "matches" : 22458,
          "failures" : 0,
          "patterns_per_field" : {
            "message" : 4
          },
          "name" : "grok"
        } ],
        "outputs" : [ {
          "id" : "4843f948c4ca7bc1623caf94a0ee4f8414143dff2179f39c0912222542a32810",
          "events" : {
            "duration_in_millis" : 489,
            "in" : 3,
            "out" : 3
          },
          "name" : "file"
        }, {
          "id" : "012630a191ae9fca3f6e3e900bc21b422ce3d4c8ba3c22839e82c3805bbe667e",
          "documents" : {
            "successes" : 251369
          },
          "events" : {
            "duration_in_millis" : 2235732,
            "in" : 251369,
            "out" : 251369
          },
          "bulk_requests" : {
            "successes" : 69169,
            "responses" : {
              "200" : 69169
            }
          },
          "name" : "elasticsearch"
        } ]
      },
      "reloads" : {
        "last_error" : null,
        "successes" : 0,
        "last_success_timestamp" : null,
        "last_failure_timestamp" : null,
        "failures" : 0
      },
      "queue" : {
        "type" : "memory"
      }
    },
    "cloudflare" : {
      "events" : {
        "duration_in_millis" : 1827546,
        "in" : 723981,
        "out" : 723981,
        "filtered" : 723981,
        "queue_push_duration_in_millis" : 385864
      },
      "plugins" : {
        "inputs" : [ {
          "id" : "2fafc1010dd2b1487a8ca1eb149b0e49cb6f49c7d78c1baf4cfc70b7d3b4826e",
          "events" : {
            "out" : 723981,
            "queue_push_duration_in_millis" : 385864
          },
          "name" : "file"
        } ],
        "filters" : [ {
          "id" : "26626f7f1fe73f149c47918ab2b64969dec3acfff6a851bd63793f0ff275e3f8",
          "events" : {
            "duration_in_millis" : 9100,
            "in" : 723981,
            "out" : 723981
          },
          "matches" : 723981,
          "name" : "date"
        }, {
          "id" : "67925bb2022455dd5f2017b2c214a9fb2e6625f85dd1091a82969baaa3a00733",
          "events" : {
            "duration_in_millis" : 3764,
            "in" : 723981,
            "out" : 723981
          },
          "name" : "mutate"
        }, {
          "id" : "4681f3b7e718e64eb3cddf4f524fe7abe454c2d7565d72e3adbb02e0635ad03c",
          "events" : {
            "duration_in_millis" : 21643,
            "in" : 723981,
            "out" : 723981
          },
          "name" : "json"
        }, {
          "id" : "3b64ee5b933c788643ba9955484fd62045e167828e73f84a556c569b5a87aa05",
          "events" : {
            "duration_in_millis" : 14256,
            "in" : 723981,
            "out" : 723981
          },
          "name" : "geoip"
        } ],
        "outputs" : [ {
          "id" : "8770d4b9f6ce8658ef70bf200c13ced6f7f99787b8c6cf443ab09379de742812",
          "documents" : {
            "successes" : 723981
          },
          "events" : {
            "duration_in_millis" : 1581033,
            "in" : 723981,
            "out" : 723981
          },
          "bulk_requests" : {
            "successes" : 5807,
            "responses" : {
              "200" : 5807
            }
          },
          "name" : "elasticsearch"
        } ]
      },
      "reloads" : {
        "last_error" : null,
        "successes" : 0,
        "last_success_timestamp" : null,
        "last_failure_timestamp" : null,
        "failures" : 0
      },
      "queue" : {
        "type" : "memory"
      }
    },
    ".monitoring-logstash" : {
      "events" : null,
      "plugins" : {
        "inputs" : [ ],
        "filters" : [ ],
        "outputs" : [ ]
      },
      "reloads" : {
        "last_error" : null,
        "successes" : 0,
        "last_success_timestamp" : null,
        "last_failure_timestamp" : null,
        "failures" : 0
      },
      "queue" : null
    }
  },
  "reloads" : {
    "successes" : 0,
    "failures" : 0
  },
  "os" : {
    "cgroup" : {
      "cpuacct" : {
        "usage_nanos" : 1922120672659,
        "control_group" : "/system.slice/logstash.service"
      },
      "cpu" : {
        "cfs_quota_micros" : -1,
        "control_group" : "/system.slice/logstash.service",
        "stat" : {
          "number_of_times_throttled" : 0,
          "time_throttled_nanos" : 0,
          "number_of_elapsed_periods" : 0
        },
        "cfs_period_micros" : 100000
      }
    }
  }
}
```

**Comment by widhalmt** [comment] 2019-03-22 19:50
The problem seems to be the `xpack.monitoring` . It's shown as a seperate pipeline but it doesn't have any events. I'll try and fix this.

**Comment by widhalmt** [comment] 2019-03-22 20:06
Version 0.7.2 will have a fix for this. Thank you for your help and patience.

**Closed** 2019-03-22 20:07 UTC

**Comment by rnicksic** [comment] 2019-03-22 20:29
Fix verified. Thanks for the quick response.

**Comment by widhalmt** [comment] 2019-03-22 21:00
Thanks for verifying. I'm trying to keep up. ;-)Am 22.03.2019 21:29 schrieb rnicksic <notifications@github.com>:Fix verified. Thanks for the quick response.
